---
title: Resources for lab leaders
output:
  html_document:
    toc: true
    toc_float: true
---

As a lab leader, you oversee the lab and are the lead of the projects. You be in charge of gathering funding and mentoring trainees more generally. Your primary responsibilities are to make sure your lab managers and lab developers are set up and supported for success.

We recommend you read through this course on [Leadership for Cancer Informatics Research](https://jhudatascience.org/Informatics_Research_Leadership/introduction.html) by Carrie Wright.

**General tips:**    
- As the leader of the lab, your job will be to help guide your lab in prioritizing code review as well as setting up the macro-system for what code review in your lab should look like.
- Where appropriate, we highly suggest you delegate all direct handling of code and code review responsibilities to others in your lab.
- If historically, you've been more directly involved with reviewing code, this means you will have to intentionally take a step back from that role and instead focus on supporting your lab members as they create a collaborative code review atmosphere of their own. Encourage your lab members to heavily communicate and collaborate with each other instead of you. This will be a more efficient use of everyone's time!

**Tips for fostering a collaborative code development atmosphere**  
- You likely will want to have a meeting with your lab to set clear expectations about what a code review system will look like in your lab. Whatever system you decide to try, keep it open and clear to your trainees that if something with this system is not working, that they should come to you so as a team you can reevaluate what may need to be tweaked.
- Set aside a special meeting time each week where members can each take turns presenting technical problems.

#### Resources for lab managers
As a lab manager, your role is to help others develop their code and you may also develop code directly yourself at times.
Your primary responsibilities are not only to help developers create code that is the least wrong, but perhaps more importantly guide the lab developer(s) technical skill development.

**General tips:**  
- As a senior member of the lab (at least when it comes to the technical aspects of code), you will want to achieve an open and empathetic communication line with the lab developers. You will be their direct support when it comes to troubleshooting or problems that arise.
- It may take time and trial and error, but you will need to work with the lab developer(s) on striking a communication balance. You want to make it clear that you are available to help whenever the lab developers are stuck; but you will also want encourage lab developers to take time to run, test, and troubleshoot. This delicate balance is something that each lab developer will need to determine with your and your lab leader's guidance.  
- As the primary reviewer of the code, it is your responsibility to ensure the correctness and efficiency of the code.   

Here are recommended reading for you:
- [Engaging in Code Review as an Author](https://jhudatascience.org/Adv_Reproducibility_in_Cancer_Informatics/engaging-in-code-review---as-an-author.html) by Candace Savonen.
- [Engaging in Code Review as an Reviewer](https://jhudatascience.org/Adv_Reproducibility_in_Cancer_Informatics/engaging-in-code-review---as-a-reviewer.html) by Candace Savonen.

#### Resources for lab developers

**General tips:**  
- As the direct author of the code you will have the most intimate knowledge of the code and project details. This means that your ability to communicate with others in your lab is critical to the smoothness and success of the project.
- It is a skill to know when to ask for help and when you should continue to plug away at a problem on your own. With the help and guidance of your lab manager and/or lab leader, you can work on striking the right balance. On one hand, if you are stuck on a problem that you are making no progress on it is an inefficient use of everyone's time and energy for you to continue to be frustrated -- **definitely reach out for help**! Others want you and your project to succeed and are generally happy to help you!
- If you are in a small lab or a lab that is not very programming proficient, you may need to get creative in finding help. At the data science lab, one of our goals will be to help you get connected with others to collaborate with.

**Recommended reading:**  

- [Engaging in Code Review as an Author](https://jhudatascience.org/Adv_Reproducibility_in_Cancer_Informatics/engaging-in-code-review---as-an-author.html) by Candace Savonen.
- [Engaging in Code Review as an Reviewer](https://jhudatascience.org/Adv_Reproducibility_in_Cancer_Informatics/engaging-in-code-review---as-a-reviewer.html) by Candace Savonen.
- [A zen manifesto for effective code reviews](https://www.freecodecamp.org/news/a-zen-manifesto-for-effective-code-reviews-e30b5c95204a/) by Jean-Charles Fabre.
- [Best practices for Code Review](https://smartbear.com/en/learn/code-review/best-practices-for-peer-code-review/) from SmartBear.
